### PR TITLE
remove cob4-1 arms and gripper

### PR DESCRIPTION
**Pull request by fmessmer**
meld'ing, merging cob4-2 setup into cob4-1 and remove arms and gripper

used by https://github.com/ipa320/cob_robots/pull/369

### CODE REVIEW

**Comment by NadiaHG** [comment]
Shouldn't  we keep the camera calibration files? Actually we are using it: https://github.com/ipa320/cob_robots/blob/indigo_dev/cob_bringup/drivers/openni2.launch#L20 . I guess that the actual values are wrong, just a copy of other calibrated cameras, but we can calibrate the cameras.

**Comment by fmessmer** [comment]
Not sure whether wrong values are better than default values....as apparently the openni node can handle the case where `file:///$(find cob_calibration_data)/$(arg robot)/calibration/cameras/$(arg name).yaml` cannot be found (see cob4-2)
Thus, as long as the cameras are not calibrated, I guess we can keep this behavior....

**Comment by NadiaHG** [comment]
Opened a new issue : https://github.com/ipa320/cob_robots/issues/372

**Comment by floweisshardt** [comment]
CR: OK (better to have no calibration files than wrong ones)

**Pull request merged**
