### PR TITLE
calibrate head camera

### PR DESCRIPTION
**Pull request by NadiaHG**

### CODE REVIEW

**Comment by NadiaHG** [comment]
this calibration was not tested because some ROS packages were missed , please don't merge.

**Comment by fmessmer** [comment]
merge #124 and retrigger travis for this PR to get "green lights"

**Review by floweisshardt — APPROVED** [review]

**Comment by fmessmer** [comment]
> this calibration was not tested because some ROS packages were missed , please don't merge.

Now it's merged...but how are missing packages related to a camera calibration? Or did you mean the travis failure? @ipa-nhg

**Comment by NadiaHG** [comment]
you have to install image_proc and the compressed* packages  to check all the topics (at least the image_flip).

I have to revert this merge, the calibration doesn't look good. --> https://github.com/ipa320/cob_calibration_data/pull/125

**Pull request merged**
