### PR TITLE
unify gitignore

### PR DESCRIPTION
**Pull request by floweisshardt**

### CODE REVIEW

**Comment by fmessmer** [comment]
Hmm, general thought...
Is it possible to "link" to a .gitignore file at a central location (ipa320/care-o-bot) so we only need to maintain one?

**Comment by fmessmer** [comment]
Ok, .gitignore is now copy-pasted from https://github.com/github/gitignore/blob/master/ROS.gitignore
Still is there a "symlink"-way to do it?

**Review by fmessmer — CHANGES_REQUESTED** [review]
Please provide similar PR to 
 - cob_environments
 - cob_extern
 - cob_gazebo_plugins
 - cob_substitute
 - schunk_modular_robotics
 - sick_flexisoft

**Comment by fmessmer** [comment]
Quoting https://github.com/ipa320/cob_navigation/pull/78#pullrequestreview-17484881

@ipa-mig 
latest change on ROS.gitignore is 3 years ago....:wink:

Maybe we should use our own template and put it in ipa320/care-o-bot

**Comment by mgruhler** [comment]
@ipa-fxm @ipa-fmw I don't like this copied over version. We should definitley create one that makes sense for us... I'd rather not clutter it too much with leftover stuff....

**Comment by floweisshardt** [comment]
@ipa-mig: can you make a suggestion?

**Comment by fmessmer** [comment]
@ipa-mig @ipa-fmw
suggestion proposed in https://github.com/ipa320/care-o-bot/pull/35

**Comment by fmessmer** [comment]
closing in favour of default ipa320 .gitignore

**Pull request closed without merging**
