### PR TITLE
Migration to package format 2

### PR DESCRIPTION
**Pull request by fmessmer**
I also fixed the ugly trailing whitespaces with 

```
find -not -path "*.git/*" -type f | xargs sed -i 's/[ \t]*$//'
```

Use [this link](https://github.com/ipa320/cob_calibration_data/pull/87?w=1) to suppress whitespace-only changes!

@ipa-fmw @ipa-nhg @ipa-mdl @ipa-mig please check whether I considered everything as discussed

### CODE REVIEW

**Comment by mgruhler** [comment]
LGTM ;-)

**Comment by mathias-luedtke** [comment]
Should we add xacro as exec_depend? It is not really necessary, but it would push the dependency to dependent packages..

**Comment by mathias-luedtke** [comment]
LGTM

**Comment by NadiaHG** [comment]
LGTM

**Pull request merged**
